import { Metadata } from "next";
import { fonts } from "./fonts";
import { Providers } from "./providers";
import NavBar from "./NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <Providers>
        <body>
          <NavBar />
          <main>{children}</main>
        </body>
      </Providers>
    </html>
  );
}
